## Game constants
ELECTRICITY_PER_FOOD: float = 0.3
ELECTRICITY_PER_GOODS: float = 0.8
ELECTRICITY_PER_POP: float = 0.2


ELECTRICITY_PER_GOODS: float = 0.8

BASE_RESOURCES_PER_PRODUCTION_CAPACITY_FOOD = 28
BASE_RESOURCES_PER_PRODUCTION_CAPACITY_GOODS = 20
BASE_RESOURCES_PER_PRODUCTION_CAPACITY_ELECTRICITY = 50
BASE_RESOURCES_PER_PRODUCTION_CAPACITY_FOSSIL_FUELS = 22